# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4981c303d5c9b52f38c126dfa29add272a5faf9e33efe8c169a9f65aed5777e8c97dcd3523aa8905d87c8d8fb5396d19c3a6039931ecae1dd3a5c61658b0ff0e

test:
  secret_key_base: c55ea8a5147fad8b028f862413c305c13aac24ce4751a1c5431772a6f25ac3e4906436306cd84fc059cbdb8295fdb805c076f7052cfbf920406ebf02b53054d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
